### ISSUE TITLE
Request: Add "Sync" functionality to global volume levels

### ISSUE THREAD

**Issue by jegasus** [BlitzKraig/fvtt-SocketSettings#1]
Currently, the UI doesn't allow the GM to set global volume levels for all other players. 

![image](https://user-images.githubusercontent.com/76404978/110886152-d0dc8c80-82ad-11eb-99c7-7876ae729e78.png)

The GM only has control over the players' volume for individual tracks. 

It would be great if there could be some kind of mechanism to force all other player's global volumes to sync with the GM's global volume settings. 

Thanks for the awesome work, btw!!!

**Comment by BlitzKraig** [comment]
Added in 0.0.3, thanks for the suggestion!
