### ISSUE TITLE
Tidy UI Error when filtering

### ISSUE THREAD

**Issue by revilowaldow** [BlitzKraig/fvtt-SocketSettings#12]
- When filtering module settings with the Tidy UI module the Sync buttons change to have the description text of the owning setting.

- When filtering by module title there is no error.

- When filtering by setting the error appears for sync buttons under existing settings, but not for sync buttons added at a whole module level.

- The error does not occur except when Tidy UI is installed. [MODULE LINK](https://github.com/sdenec/tidy-ui_game-settings )

![image](https://user-images.githubusercontent.com/52298102/120894120-c9a7ef00-c60e-11eb-9172-45f5aa820c81.png)

**Comment by BlitzKraig** [comment]
Hi,
I've seen this error myself, but honestly I'm not sure what causes it or how to fix it. My guess is that tidy UI is doing something strange when filtering.

In short, I don't think it's worth the time and effort to hack together a fix for this.

**Comment by sdenec** [comment]
I can't reproduce this error. And honestly I can't explain what would cause this. I'm not doing anything fancy here, just hiding complete sections by its title. But I'm a bit confused regarding the screenshot. Looks like there are two search fields?
That's how it "should" tm look like - I chose the provided example to conform it is working (for me)
![working](https://user-images.githubusercontent.com/8881200/127775376-94b685b5-b5e5-487a-84bb-d0e3635675f9.jpg)

**Comment by sdenec** [comment]
Looking at it now there seems to be a few other modules at work with the colored borders and icons. I suspect there is more at work here if the error still exists.

**Comment by revilowaldow** [comment]
Had a closer look, the incompatibility is between "DF Settings Clarity" and "Socket Settings"
