### ISSUE TITLE
Incompatibility with DF Settings Clarity

### ISSUE THREAD

**Issue by revilowaldow** [BlitzKraig/fvtt-SocketSettings#13]
When installed at the same time as DF Settings clarity all of the sync buttons display incorrect (or no) text, whether filtering or not.

![image](https://user-images.githubusercontent.com/52298102/127780705-0188355f-53e7-4ef0-8335-036ad498c4ce.png)

**Comment by revilowaldow** [comment]
See also: https://github.com/flamewave000/dragonflagon-fvtt/issues/166

**Comment by flamewave000** [comment]
I'm not sure what the conflict is here. I don't touch anything in the layout for settings, I just append the world🌎 and person👤 emojis to the setting's Name text. It appears the SocketSettings is attempting to use the "Hint" text for its button label, but is displaying "Sync" when the Hint text is not defined or maybe empty? Not sure how Settings Clarity adding an emoji to the Name field would interrupt the behaviour, but let me know if you see something out of place 👍🏽

**Comment by BlitzKraig** [comment]
For clarity, SocketSettings should be displaying "Sync". For some reason, it seems to instead grab the hint text when DF Settings Clarity is installed. I'll find some time soon to see if I can dig into this.

**Comment by BlitzKraig** [comment]
Took another look at this. I use the `notes` css class in my buttons css.
I'm assuming DF Settings Clarity runs some JQuery when filtering to populate the settings hint, which can only be identified by that CSS class, causing my button to also receive the hint text.

I removed the notes class from my button, and can confirm the issue disappears.
I'm going to remove it, and add any styling I needed from it into my own CSS.

Thanks

**Comment by BlitzKraig** [comment]
Fixed in 0.6.6
