### ISSUE TITLE
Add option to sync all settings at once

### ISSUE THREAD

**Issue by BlitzKraig** [BlitzKraig/fvtt-SocketSettings#2]
Was hesitant to add this, but had a few requests

**Comment by brunocalado** [comment]
Imagine sync dozens of modules lol 

Please do it!

Thank you;

![image](https://user-images.githubusercontent.com/4999783/122659434-92792800-d14e-11eb-8358-86aaf44e1232.png)

**Comment by BlitzKraig** [comment]
Added in 0.0.7
